sync-data: ensure source host is provided
Required for RockyLinux8 but not Ubuntu, weird.

On Ubuntu, if can not shift, we have an error.

diff --git a/birdhouse/scripts/sync-data b/birdhouse/scripts/sync-data
--- a/birdhouse/scripts/sync-data
+++ b/birdhouse/scripts/sync-data
@@ -28,6 +28,11 @@ fi
 SOURCE_HOST="$1"; shift
 FORCE_MODE="$1"
 
+if [ -z "$SOURCE_HOST" ]; then
+    echo "ERROR: no source host provided" 1>&2
+    exit 2
+fi
+
 if [ ! x"$FORCE_MODE" = xforce ]; then
     # Default to dry-run
     SYNC_DATA_EXTRA_RSYNC_OPTS="$SYNC_DATA_EXTRA_RSYNC_OPTS --dry-run"
