deploy-data: fix error checking always exit even if no error
+ git clone https://github.com/Ouranosinc/raven /data/deploy_data_cache/deploy_raven_testdata_to_thredds/raven
Cloning into '/data/deploy_data_cache/deploy_raven_testdata_to_thredds/raven'...
Updating files:  89% (344/383)^MUpdating files:  90% (345/383)^MUpdating files:  91% (349/383)^MUpdating files:  92% (353/383)^MUpdating files:  93% (357/383)^MUpdating files:  94% (361/383)^MUpdating files:  95% (364/383)^MUpdating files:  96% (368/383)^MUpdating files:  97% (372/383)^MUpdating files:  98% (376/383)^MUpdating files:  99% (380/383)^MUpdating files: 100% (383/383)^MUpdating files: 100% (383/383), done.
+ exit 1

diff --git a/birdhouse/deployment/deploy-data b/birdhouse/deployment/deploy-data
--- a/birdhouse/deployment/deploy-data
+++ b/birdhouse/deployment/deploy-data
@@ -110,7 +110,7 @@ for GIT_REPO_URL in $GIT_REPO_URLS; do
     CLONE_DEST="$CHECKOUT_CACHE/$GIT_CHECKOUT_NAME"
     if [ ! -d "$CLONE_DEST" ]; then
         echo "checkout repo '$GIT_REPO_URL' on branch '$GIT_BRANCH' to '$CLONE_DEST'"
-        git clone $GIT_REPO_URL $CLONE_DEST || echo "git clone failed" 1>&2 ; exit 1
+        git clone $GIT_REPO_URL $CLONE_DEST || echo "git clone failed" 1>&2 && exit 1
         cd $CLONE_DEST
         git checkout $GIT_BRANCH
     else
@@ -118,7 +118,7 @@ for GIT_REPO_URL in $GIT_REPO_URLS; do
         cd $CLONE_DEST
         git remote -v  # log remote, should match GIT_REPO_URL
         git clean -fdx  # force, recur dir, also clean .gitignore files and untracked files
-        git fetch --prune --all || echo "git fetch failed" 1>&2 ; exit 1
+        git fetch --prune --all || echo "git fetch failed" 1>&2 && exit 1
         git checkout --force $GIT_BRANCH  # force checkout to throwaway local changes
     fi
 
