multiple fixes on script and env.local after PR feedback

diff --git a/birdhouse/deployment/deploy-data-specific-image b/birdhouse/deployment/deploy-data-specific-image
--- a/birdhouse/deployment/deploy-data-specific-image
+++ b/birdhouse/deployment/deploy-data-specific-image
@@ -13,8 +13,6 @@
 #
 # One or more entries respecting this format can be added to the yaml file, in order to download multiple file/folders.
 #
-# An installation of jq and yq is preferred prior to executing this script.
-#
 # Setting environment variable DEPLOY_DATA_LOGFILE='/path/to/logfile.log'
 # will redirect all STDOUT and STDERR to that logfile so this script will be
 # completely silent.
@@ -32,53 +30,52 @@ START_TIME="`date -Isecond`"
 echo "==========
 deploy-data-specific-image START_TIME=$START_TIME"
 
-CONFIG_YML="$1"
-if [ -z "$CONFIG_YML" ]; then
+CONFIG_YML_PATH="$1"
+if [ -z "$CONFIG_YML_PATH" ]; then
     echo "ERROR: missing config.yml file" 1>&2
     exit 2
 fi
 
+# Checks if the config has a required parameter value, takes the string name of the env variable to evaluate as input.
 # Empty value could mean typo in the keys in the config file.
 ensure_not_null() {
-    if [ "$*" = null ]; then
-        echo "ERROR: value empty" 1>&2
+    if [ "${!1}" = null ]; then
+        echo "ERROR: empty $1 value found in the config file" 1>&2
         exit 1
     fi
 }
 
 # Check installation of required package to read yaml files
-if ! command -v jq &> /dev/null; then
-  apt-get -y install jq
-fi
 if ! command -v yq &> /dev/null; then
-  pip install yq
+    echo "ERROR: missing yq package installation" 1>&2
+    exit 1
 fi
 
 # Find how many entries are in the config file
-LENGTH="`yq -r '. | length' $CONFIG_YML`"
+CONFIG_LIST_LENGTH="`yq -r '. | length' $CONFIG_YML_PATH`"
 
-if [ -z $LENGTH ]; then
+if [ -z $CONFIG_LIST_LENGTH ]; then
     echo "ERROR: empty config file" 1>&2
     exit 1
 fi
 
-for ((i=0;i<$LENGTH;i++)); do
-  # Extract data from config
-  GIT_REPO="`yq -r .[$i].repo_url $CONFIG_YML`"
-  ensure_not_null "$GIT_REPO"
+for ((i=0;i<$CONFIG_LIST_LENGTH;i++)); do
+    # Extract data from config
+    GIT_REPO="`yq -r .[$i].repo_url $CONFIG_YML_PATH`"
+    ensure_not_null "GIT_REPO"
 
-  BRANCH="`yq -r .[$i].branch $CONFIG_YML`"
-  ensure_not_null "$BRANCH"
+    BRANCH="`yq -r .[$i].branch $CONFIG_YML_PATH`"
+    ensure_not_null "BRANCH"
 
-  SOURCE_PATH="`yq -r .[$i].source_path $CONFIG_YML`"
-  ensure_not_null "$SOURCE_PATH"
+    SOURCE_PATH="`yq -r .[$i].source_path $CONFIG_YML_PATH`"
+    ensure_not_null "SOURCE_PATH"
 
-  FULL_URL=$GIT_REPO/branches/$BRANCH/$SOURCE_PATH
+    FULL_URL=$GIT_REPO/branches/$BRANCH/$SOURCE_PATH
 
-  echo "Extracting ${FULL_URL} to ${NOTEBOOK_DEST_DIR}"
+    echo "Extracting ${FULL_URL} to ${NOTEBOOK_DEST_DIR}"
 
-  # Download the data from github and copy it to the destination directory
-  svn export --force $FULL_URL $NOTEBOOK_DEST_DIR
+    # Download the data from github and copy it to the destination directory
+    svn export --force $FULL_URL $NOTEBOOK_DEST_DIR
 done
 
 echo "notebookdeploy finished   END_TIME=`date -Isecond`"
