revert read-configs.include.sh move + unify variables/escapes/quote-exec

diff --git a/birdhouse/deployment/install-deploy-notebook b/birdhouse/deployment/install-deploy-notebook
--- a/birdhouse/deployment/install-deploy-notebook
+++ b/birdhouse/deployment/install-deploy-notebook
@@ -21,21 +21,21 @@ if [ -z "$1" ]; then
 fi
 
 
-REPO_ROOT="`realpath "$1"`"; shift  # path to PAVICS checkout
+REPO_ROOT="$(realpath "$1")"; shift  # path to PAVICS checkout
 
-if [ ! -e "$REPO_ROOT/birdhouse/deployment/trigger-deploy-notebook" ]; then
-    echo "ERROR: bad/wrong pavics-checkout '$REPO_ROOT' " 1>&2
+if [ ! -e "${REPO_ROOT}/birdhouse/deployment/trigger-deploy-notebook" ]; then
+    echo "ERROR: bad/wrong pavics-checkout '${REPO_ROOT}' " 1>&2
     usage
     exit 2
 fi
 
-. "$REPO_ROOT/birdhouse/scripts/read-configs.include.sh"
+. "${REPO_ROOT}/birdhouse/read-configs.include.sh"
 
 # Get JUPYTERHUB_USER_DATA_DIR
 read_configs
 
 set -x
 
-cat $REPO_ROOT/birdhouse/deployment/trigger-deploy-notebook | envsubst '${JUPYTERHUB_USER_DATA_DIR}' | sudo tee $CRON_FILE
-sudo chown root:root $CRON_FILE
-sudo chmod 755 $CRON_FILE
+cat "${REPO_ROOT}/birdhouse/deployment/trigger-deploy-notebook" | envsubst '${JUPYTERHUB_USER_DATA_DIR}' | sudo tee "${CRON_FILE}"
+sudo chown root:root "${CRON_FILE}"
+sudo chmod 755 "${CRON_FILE}"
